version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vite-app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      # - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["bun", "run", "dev"]
